// Pixel maps for the Level Up intro. One character per pixel; '.' is transparent.
//   k black · i ink · p plum · c crimson · r brand red · e ember · m cream · w white · y gold · o amber · s skin · g steel
const PAL_KEYS = 'kipcremwyosg';
const PALETTE = [
  [0, 0, 0],        // k  black
  [19, 6, 12],      // i  ink
  [45, 12, 29],     // p  plum
  [75, 0, 17],      // c  dark crimson #4B0011
  [184, 0, 22],     // r  brand red #B80016
  [255, 84, 64],    // e  ember
  [247, 230, 196],  // m  cream
  [255, 255, 255],  // w  white
  [255, 194, 26],   // y  gold (XP)
  [196, 106, 0],    // o  amber
  [232, 160, 122],  // s  skin
  [106, 85, 96],    // g  steel
];
const SPRITES = {
  // ── ZERO: LV 0, ginger hair, grey tee, nervous eyes ──
  zero: [
    '......kkkkk.....',
    '....kkooyookk...',
    '...koooooooyok..',
    '..koooooooooook.',
    '..kooooooooooook',
    '..koooookoookook',
    '..kooookskssksk.',
    '..koookssssssssk',
    '..kookssmkssmksk',
    '...kokssmkssmksk',
    '...kksssssssssk.',
    '....ksssskkkssk.',
    '.....kssssssk...',
    '......kkskkk....',
    '.....kggggggk...',
    '....kggggggggk..',
    '...kgggggggggk..',
    '...kgggggggggk..',
    '...kgggggggggk..',
    '...kgggggggggk..',
    '...kgggggggggk..',
    '....kgggggggk...',
    '....kpppppppk...',
    '....kpppppppk...',
    '....kpppkpppk...',
    '....kppk.kppk...',
    '....kppk.kppk...',
    '....kppk.kppk...',
    '...kmmmk.kmmmk..',
    '..kmmmmk.kmmmmk.',
    '..kkkkk..kkkkkk.',
  ],
  // the zero's guitar and arms, two strum frames (hand up / hand down); same origin as the body
  zeroGtrA: [
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '.......................kk.',
    '......................krrk',
    '.....................kmrk.',
    '..kk...........kk..kkook..',
    '.kggk.........kgsk.kook...',
    '.kgsk........kgkssooook...',
    '..kssk.....kkk.kssook.....',
    '..kssskk.kkook..kkk.......',
    '.krkssskkooook............',
    'krrrkkkooook..............',
    'krrmmrrook................',
    '.krmkkrrk.................',
    'krrmmmmrrrk...............',
    'krrrrrrrrrk...............',
    '.krrrrrrrk................',
    '..kkkkkkk.................',
  ],
  zeroGtrB: [
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '.......................kk.',
    '......................krrk',
    '.....................kmrk.',
    '..kk...........kk..kkook..',
    '.kggk.........kgsk.kook...',
    '.kgsk........kgkssooook...',
    '.ksk.......kkk.kssook.....',
    '.kssk....kkook..kkk.......',
    '.krsk..kkooook............',
    'krrrkkkooook..............',
    'krrmksskk.................',
    '.krmksssk.................',
    'krrmmkskrrk...............',
    'krrrrrrrrrk...............',
    '.krrrrrrrk................',
    '..kkkkkkk.................',
  ],
  // ── HERO: LV 99, gold spikes, shades, leather jacket, red cape ──
  hero: [
    '.k.......k........',
    '.yk.....kyk.......',
    '.kyk...kyyyk..kk..',
    '..kyyk.kyyyykkyyk.',
    '.kyyyyykyyyyyyyyk.',
    'kyyyoyyyyyyyyyyyyk',
    '.kyyyyyyyoyyyyyyk.',
    '..kyyyyoyyyyyyyyk.',
    '..kyyykkkkkkkkkkkk',
    '..kyykkkwkkkkwkkk.',
    '..kyoksskkkssskk..',
    '...kokssssssssk...',
    '....ksskwwwwwsk...',
    '.....ksskkkkk.....',
    '....kkkssssk......',
    '...kkgkrrrrkgk....',
    '..kgkkkrrrrkkkgk..',
    '..kgkkgrrrrgkkgk..',
    '..kgkkgrrrrgkkgk..',
    '..kgkkkrrrrkkkgk..',
    '..kgkkkkrrkkkkgk..',
    '..kgkkkkkkkkkkgk..',
    '...kkkkkkkkkkkk...',
    '...kyyyyyyyyyyk...',
    '...kgggggggggggk..',
    '...kgggkkkkgggk...',
    '...kgggk..kgggk...',
    '...kgigk..kgigk...',
    '...kgggk..kgggk...',
    '..kkkkkk..kkkkkk..',
    '..kkmkkk..kmkkkk..',
    '..kkkkkk..kkkkkkk.',
  ],
  // flying-V guitar and arms, two strum frames
  heroGtrA: [
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '.........................kk.',
    '........................kmmk',
    '.......................kyyk.',
    '......................kymk..',
    '...kk.............kk.kook...',
    '..kgkk...........kgkkook....',
    '..kgkk..........kgkkoook....',
    '..kgksk.......kkkkssook.....',
    '...kssk.....kkook.sskk......',
    'kk..ksssk.kkoook...kk.......',
    'kyykkksskooook..............',
    '.kymyykkooook...............',
    '..kyyyyook..................',
    '..kymyyyk...................',
    '.kyyyyyyyk..................',
    'kyyykkkkyyk.................',
    'kyyk....kyk.................',
    'kkk......kk.................',
  ],
  heroGtrB: [
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '.........................kk.',
    '........................kmmk',
    '.......................kyyk.',
    '......................kymk..',
    '...kk.............kk.kook...',
    '..kgkk...........kgkkook....',
    '..kgkk..........kgkkoook....',
    '..kgkk........kkkkssook.....',
    '..kgkk......kkook.sskk......',
    'kk.kgkk...kkoook...kk.......',
    'kyykgkkkkooook..............',
    '.kymksskooook...............',
    '..kyksssk...................',
    '..kymksskk..................',
    '.kyyyykkyyk.................',
    'kyyykkkkyyk.................',
    'kyyk....kyk.................',
    'kkk......kk.................',
  ],
  // cape behind the hero, three flutter frames
  cape0: [
    '.......kkk.....',
    '.....kkrrk.....',
    '....krrrrk.....',
    '...krrrrrk.....',
    '..krrrrcrk.....',
    '..krrrcrrk.....',
    '.krrrrcrrk.....',
    '.krrrcrrrk.....',
    'krrrrcrrrk.....',
    'krrrcrrrrk.....',
    'kcrrcrrrck.....',
    '.kccrcrcck.....',
    '..kkckcckk.....',
    '....k.kk.......',
  ],
  cape1: [
    '.......kkk.....',
    '......krrk.....',
    '.....krrrk.....',
    '....krrrrk.....',
    '...krrrcrk.....',
    '..krrrcrrk.....',
    '..krrrcrrk.....',
    '.krrrcrrrk.....',
    '.krrrcrrrk.....',
    'krrrcrrrrk.....',
    'krrrcrrrck.....',
    'kcrcrrrcck.....',
    '.kkcrcckk......',
    '...kkk.........',
  ],
  cape2: [
    '.......kkk.....',
    '......krrk.....',
    '.....krrrk.....',
    '.....krrrk.....',
    '....krrcrk.....',
    '....krrcrk.....',
    '...krrcrrk.....',
    '...krrcrrk.....',
    '..krrcrrrk.....',
    '..krrcrrrk.....',
    '.krrcrrrrk.....',
    '.kcrcrrrck.....',
    'kccrcccck......',
    '.kkkkkk........',
  ],
  sweat: ['.m.', 'mwm', '.m.'],
  // stage gear
  amp: [
    'kkkkkkkkkkkkkkkkkkkk',
    'kiiiiiiiiiiiiiiiiiik',
    'kiyyyyyiimiimiimiiik',
    'kiiiiiiiiiiiiiiiiiik',
    'kkkkkkkkkkkkkkkkkkkk',
    'kmmmmmmmmmmmmmmmmmmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmmmmmmmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkkkkkkkk',
    '.kk..............kk.',
  ],
  cab: [
    'kkkkkkkkkkkkkkkkkkkk',
    'kmmmmmmmmmmmmmmmmmmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcggggpcpcpggggpcmk',
    'kmgiiiigpcpgiiiigcmk',
    'kmgikkigcpcgikkigpmk',
    'kmgikkigpcpgikkigcmk',
    'kmgiiiigcpcgiiiigpmk',
    'kmcggggpcpcpggggpcmk',
    'kmpcpcpcpcpcpcpcpcmk',
    'kmcpcpcpcpcpcpcpcpmk',
    'kmmmmmmmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkkkkkkkk',
    '.kk..............kk.',
  ],
  tinyAmp: [
    '.kkkkkkkkk.',
    'kgggggggggk',
    'kgymgmgmggk',
    'kkkkkkkkkkk',
    'kgcpcpcpcgk',
    'kgpcpcpcpgk',
    'kgcpcpcpcgk',
    'kgggggggggk',
    'kkkkkkkkkkk',
  ],
  lamp: ['.kkkkk.', 'kgggggk', 'kgigigk', 'kkkkkkk', '.kyyyk.'],
  note: ['..kk.', '..kyk', '..k.k', '..k..', 'kkk..', 'kkk..', '.k...'],
  note2: ['.kkkkk', '.k...k', '.k...k', '.k...k', 'kk..kk', 'kk..kk', '......'],
  star: ['..w..', '..m..', 'wmwmw', '..m..', '..w..'],
  star2: ['.w.', 'www', '.w.'],
  coin0: ['..kkkk..', '.kyyyyk.', 'kyywyyok', 'kyyyyyok', 'kyyyyyok', 'kyyyyook', '.kooook.', '..kkkk..'],
  coin1: ['..kkk...', '.kyyyk..', '.kywyok.', '.kyyyok.', '.kyyyok.', '.kyyook.', '.kooook.', '..kkk...'],
  coin2: ['...kk...', '...kk...', '...yk...', '...yk...', '...yk...', '...ok...', '...kk...', '...kk...'],
  // a raised fist making the rock horns, for the crowd
  horns: ['k...k', 'k...k', 'kkkkk', 'kkkkk', '.kkk.', '.kkk.', '.kkk.'],
  fist: ['.kkk.', 'kkkkk', 'kkkkk', '.kkk.', '.kkk.', '.kkk.'],
  flame0: ['...e....', '..eye...', '..eyye..', '.eywye..', '.eywwye.', 'eyywwyre', 'reyyyerr', '.rreerr.'],
  flame1: ['....e...', '...eye..', '..eyye..', '..eywye.', '.eyywwe.', 'reywwyye', 'rreyyerr', '.rreerr.'],
  flame2: ['..e.....', '..ee.e..', '.eyeeye.', '.eywyye.', 'eywwwyye', 'eyywwyer', 'rreyyerr', '.rrreer.'],
  pick: ['kkkkkkk', 'krrrrrk', 'krmrrrk', '.krrrk.', '.krrk..', '..kk...'],
  zeroArms: [
    '.kkk................kkk.',
    'ksssk..............ksssk',
    'ksssk..............ksssk',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '.kssk..............kssk.',
    '..kssk............kssk..',
    '..kssk............kssk..',
    '..kssk............kssk..',
    '...kssk..........kssk...',
    '...kssk..........kssk...',
    '....kssk........kssk....',
    '....kssk........kssk....',
    '.....kggk......kggk.....',
    '.....kggk......kggk.....',
    '......kggk....kggk......',
    '......kgggk..kgggk......',
  ],
  heroArms: [
    '.kkk................kkk.',
    'ksssk..............ksssk',
    'ksssk..............ksssk',
    '.kkkk..............kkkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '.kgkk..............kgkk.',
    '..kgkk............kgkk..',
    '..kgkk............kgkk..',
    '..kgkk............kgkk..',
    '...kgkk..........kgkk...',
    '...kgkk..........kgkk...',
    '....kgkk........kgkk....',
    '....kgkk........kgkk....',
    '.....kgkk......kgkk.....',
    '.....kgkk......kgkk.....',
    '......kgkk....kgkk......',
    '......kgkkk..kkkgk......',
  ],
  itemGtr: [
    '...........kk.',
    '..........kmmk',
    '.........kook.',
    '........kook..',
    '.......kook...',
    '......kook....',
    '..kkk.kok.....',
    '.krrrkok......',
    'krrmrrok......',
    'krmmrrrk......',
    '.krmmrrrk.....',
    'krrrrrrrk.....',
    'krrrrrrk......',
    '.kkkkkk.......',
  ],
  itemPedal: [
    '.kkkkkkkkkkkk.',
    'krrrrrrrrrrrrk',
    'krmrrmrrmrrrrk',
    'krkrrkrrkrrrrk',
    'krrrrrrrrrryrk',
    'kreeeeeeeeeeek',
    'krrrrkkkkrrrrk',
    'krrrrkggkrrrrk',
    'krrrrkkkkrrrrk',
    'kcccccccccccck',
    '.kkkkkkkkkkkk.',
  ],
  itemAmp: [
    'kkkkkkkkkkkkkk',
    'kiyiimimimiiik',
    'kkkkkkkkkkkkkk',
    'kmmmmmmmmmmmmk',
    'kmggggmmggggmk',
    'kmgiigmmgiigmk',
    'kmgiigmmgiigmk',
    'kmggggmmggggmk',
    'kmmmmmmmmmmmmk',
    'kmggggmmggggmk',
    'kmgiigmmgiigmk',
    'kmgiigmmgiigmk',
    'kmggggmmggggmk',
    'kmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkk',
  ],
  itemCape: [
    '...kkkkkkkk...',
    '..kyrrrrrryk..',
    '..kryyyyyyrk..',
    '.krrrrrrrrrrk.',
    '.krrrcrrcrrrk.',
    '.krrrcrrcrrrk.',
    'krrrrcrrcrrrrk',
    'krrrcrrrrcrrrk',
    'krrrcrrrrcrrrk',
    'krrcrrrrrrcrrk',
    'kcrcrrcrrcrcrk',
    '.kckcckcckckk.',
    '..k.kk.kk.k...',
  ],
  itemAxe: [
    '............kk',
    '...........kwk',
    '..........kywk',
    '.........kyyk.',
    '........kook..',
    '.......kook...',
    '..k...kook....',
    '.kyk.kook.....',
    'kywykyok......',
    'kyyyyyk.......',
    '.kymyk........',
    '.kyyyyk.......',
    'kyykkyyk......',
    'kyk..kyk......',
    'kk....kk......',
  ],
  iconGtr: [
    '.....kk',
    '....kok',
    '...kok.',
    'kkkok..',
    'krrok..',
    'krmrk..',
    '.kkk...',
  ],
  iconPedal: [
    'kkkkkkk',
    'kmrmrmk',
    'krrrrrk',
    'kreeeek',
    'krrkrrk',
    'krkgkrk',
    'kkkkkkk',
  ],
  iconAmp: [
    'kkkkkkk',
    'kymymyk',
    'kkkkkkk',
    'kgpgpgk',
    'kpgpgpk',
    'kgpgpgk',
    'kkkkkkk',
  ],
  iconCape: [
    '.kyyyk.',
    'krrrrrk',
    'krrcrrk',
    'krrcrrk',
    'krcrcrk',
    'kcrcrck',
    '.k.k.k.',
  ],
  iconAxe: [
    '.....kw',
    '....kyk',
    '...kok.',
    'kykok..',
    'kyyk...',
    '.kmyk..',
    'kyk.k..',
  ],
  mapZero: [
    '..kkk..',
    '.kooook',
    'kooooo.',
    'ksssok.',
    '.ksssk.',
    'kggggk.',
    'kggggk.',
    '.kppk..',
    '.kmmk..',
  ],
  mapHero: [
    '.k.k.k.',
    'kyykyyk',
    'kyyyyyk',
    'kkkkkk.',
    '.ksssk.',
    'rkkrkk.',
    'rkrrkk.',
    'r.kggk.',
    '..kkk..',
  ],
  nodeHouse: [
    '......kk......',
    '.....krrk.....',
    '....krrrrk....',
    '...krrrrrrk...',
    '..krrrrrrrrk..',
    '.kkkkkkkkkkkk.',
    '..kmmmmmmmmk..',
    '..kmyykmmmmk..',
    '..kmyykmkkmk..',
    '..kmmmmmkomk..',
    '..kmmmmmkomk..',
    '..kkkkkkkkkk..',
  ],
  nodeCafe: [
    '...m...m......',
    '....m...m.....',
    '...m...m......',
    '..kkkkkkkkk...',
    '..kmmmmmmmkkk.',
    '..kmmmmmmmk.k.',
    '..kmmrrrmmk.k.',
    '..kmmmmmmmkkk.',
    '..kmmmmmmmk...',
    '...kmmmmmk....',
    '.kkkkkkkkkkk..',
    '..kkkkkkkkk...',
  ],
  nodeBar: [
    '..mmmmmmm.....',
    '.mmmmmmmmm....',
    '.kkkkkkkkkk...',
    '.kyyyyyyyykkk.',
    '.kyoyyyyyyk.k.',
    '.kyoyyyyyyk.k.',
    '.kyoyyyyyyk.k.',
    '.kyoyyyyyykkk.',
    '.kyyyyyyyyk...',
    '.kkkkkkkkkk...',
  ],
  nodeArena: [
    '......y.......',
    '......kk......',
    '.....krrk.....',
    '...kkrrrrkk...',
    '..krrmrrmrrk..',
    '.krrrmrrmrrrk.',
    'krrrrmrrmrrrrk',
    'kmmmmmmmmmmmmk',
    'kmkkmmkkmmkkmk',
    'kmkkmmkkmmkkmk',
    'kkkkkkkkkkkkkk',
  ],
  nodeStadium: [
    'y............y',
    'k............k',
    'k.kkkkkkkkkk.k',
    'kkmmmmmmmmmmkk',
    'kmggggggggggmk',
    'kmgccccccccgmk',
    'kmgcrrrrrrcgmk',
    '.kmggggggggmk.',
    '..kmmmmmmmmk..',
    '...kkkkkkkk...',
  ],
  flag: [
    'kyyy',
    'kyyy',
    'kyy.',
    'k...',
    'k...',
    'k...',
  ],
  poster: [
    'kkkkkkkkkkkkkkkkkk',
    'kcccccccccccccccck',
    'kcccyccccycccyccck',
    'kccckyccyykcyyccck',
    'kcckyyyyyyyyyyccck',
    'kcckyyyyyyyyyyyccc',
    'kccckkkkkkkkkkkcck',
    'kccckwkkkkkwkkkcck',
    'kcccksskssssskccck',
    'kccccskwwwwwskccck',
    'kccccksskkkkkcccck',
    'kccrrkkrrrrkkrrcck',
    'kcrrkgkrrrrkgkrrck',
    'kcrrkgkrrrrkgkrrck',
    'kcrrkkkkkkkkkkrrck',
    'kcrrrkyyyyyykrrrck',
    'kccrrkggggggkrrcck',
    'kccckggkkkggkcccck',
    'kccckggkckggkcccck',
    'kcccccccccccccccck',
    'kcmmcmmmcmmmcmmcck',
    'kcccccccccccccccck',
    'kkkkkkkkkkkkkkkkkk',
  ],
  boss0: [
    '..........kk..................kk..........',
    '.........kck..................kck.........',
    '.........kcck................kcck.........',
    '........kcick................kcick........',
    '........kciik.....kkkkkk....kciik........',
    '.......kciiikkkkkkiiiiiikkkkkiiik.........',
    '.......kciiiiiiiiiiiiiiiiiiiiiiik.........',
    '......kciiiiiiiiiiiiiiiiiiiiiiiiik........',
    '......kciiiwwwwiiiiiiiiiwwwwiiiiik........',
    '.....kciiiwwwwwwiiiiiiwwwwwwiiiiiik.......',
    '.....kciiiwweewwiiiiiiwweewwiiiiiik.......',
    '.....kciiiwweewwiiiiiiwweewwiiiiiik.......',
    '.....kciiiiwwwwiiiiiiiiwwwwiiiiiiik.......',
    '.....kciiiiiiiiiiiiiiiiiiiiiiiiiiik.......',
    '....kciiiikkkkkkkkkkkkkkkkkiiiiiiiik......',
    '....kciiikwkwkwkwkwkwkwkwkkiiiiiiiik......',
    '....kciiikkkkkkkkkkkkkkkkkkiiiiiiiik......',
    '....kciiiikwkwkwkwkwkwkwkkiiiiiiiiik......',
    '...kciiiiiikkkkkkkkkkkkkkiiiiiiiiiiik.....',
    '..kcciiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '.kcciikciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kccik.kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kcik..kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kgk...kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'gkg...kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'g.g...kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    '.......kciiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '.......kciiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '........kciiiiiiiiiiiiiiiiiiiiiiiiik......',
    '........kciiiiiiiiiiiiiiiiiiiiiiiiik......',
    '.........kciiiiiiiiiiiiiiiiiiiiiiik.......',
    '.........kciiiiiiiiiiiiiiiiiiiiiiik.......',
    '..........kciiiiiiiiiiiiiiiiiiiiik........',
    '..........kciiiiiiikiiiiiikiiiiik.........',
    '...........kciiiiikkiiiiikkiiiik..........',
    '...........kciiiik.kiiiik.kiiik...........',
    '............kciik..kiiik..kiik............',
    '............kcik....kik....kik............',
    '.............kk.....kk......kk............',
  ],
  boss1: [
    '..........kk..................kk..........',
    '.........kck..................kck.........',
    '.........kcck................kcck.........',
    '........kcick................kcick........',
    '........kciik.....kkkkkk....kciik........',
    '.......kciiikkkkkkiiiiiikkkkkiiik.........',
    '.......kciiiiiiiiiiiiiiiiiiiiiiik.........',
    '......kciiiiiiiiiiiiiiiiiiiiiiiiik........',
    '......kciiiwwwwiiiiiiiiiwwwwiiiiik........',
    '.....kciiiwwwwwwiiiiiiwwwwwwiiiiiik.......',
    '.....kciiiwweewwiiiiiiwweewwiiiiiik.......',
    '.....kciiiwweewwiiiiiiwweewwiiiiiik.......',
    '.....kciiiiwwwwiiiiiiiiwwwwiiiiiiik.......',
    '.....kciiiiiiiiiiiiiiiiiiiiiiiiiiik.......',
    '....kciiiikkkkkkkkkkkkkkkkkiiiiiiiik......',
    '....kciiikwkwkwkwkwkwkwkwkkiiiiiiiik......',
    '....kciiikeeeeeeeeeeeeeeekkiiiiiiiik......',
    '....kciiikeeeeeeeeeeeeeeekiiiiiiiiik......',
    '....kciiiikwkwkwkwkwkwkwkkiiiiiiiiik......',
    '...kciiiiiikkkkkkkkkkkkkkiiiiiiiiiiik.....',
    '..kcciiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '.kcciikciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kccik.kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kcik..kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'kgk...kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    'gkg...kciiiiiiiiiiiiiiiiiiiiiiiiiiiiik....',
    '.......kciiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '.......kciiiiiiiiiiiiiiiiiiiiiiiiiiik.....',
    '........kciiiiiiiiiiiiiiiiiiiiiiiiik......',
    '........kciiiiiiiiiiiiiiiiiiiiiiiiik......',
    '.........kciiiiiiiiiiiiiiiiiiiiiiik.......',
    '.........kciiiiiiiiiiiiiiiiiiiiiiik.......',
    '..........kciiiiiiiiiiiiiiiiiiiiik........',
    '..........kciiiiiiikiiiiiikiiiiik.........',
    '...........kciiiiikkiiiiikkiiiik..........',
    '...........kciiiik.kiiiik.kiiik...........',
    '............kciik..kiiik..kiik............',
    '............kcik....kik....kik............',
    '.............kk.....kk......kk............',
  ],
  wing0: [
    '...............ee.....',
    '.........e....eyye....',
    '........eye..eyywe.e..',
    '...e...eywe.eyywe.eye.',
    '..eye..eywe.eywwe.eywe',
    '..eywe.eywweywwe.eywe.',
    '...eywe.eywwywe.eywwe.',
    '...eywwe.eywwwe.eywe..',
    '....eywwe.eywweeywwe..',
    '.....eywwe.eywwywwe...',
    '......eywweeywwwwe....',
    '.......reywwywwwe.....',
    '.......rreywwwwye.....',
    '........rreywwye......',
    '.........rreyye.......',
    '..........rree........',
  ],
  wing1: [
    '..............e.......',
    '..........e..eye...e..',
    '.........eye.eywe.eye.',
    '..e.....eywe.eywe.eywe',
    '.eye...eywe.eywwe.eye.',
    '.eywe..eywweywwe.eywe.',
    '..eywe.eywwywwe.eywwe.',
    '...eywe.eywwwe.eywwe..',
    '....eywwe.eywweeywe...',
    '.....eywwe.eywwywwe...',
    '......eywweeywwwwe....',
    '.......reywwywwwe.....',
    '.......rreywwwwye.....',
    '........rreywwye......',
    '.........rreyye.......',
    '..........rree........',
  ],
  mug: [
    'mmmm.',
    'yyyyk',
    'yyyyk',
    'yyyyk',
    'kkkk.',
  ],
  cricket: [
    '.k.k..',
    'kgggk.',
    '.k.k.k',
  ],
};
if (typeof module !== 'undefined') module.exports = { PAL_KEYS, PALETTE, SPRITES };
